/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.amsistemas.os.telas;

import java.sql.*;
import br.com.amsistemas.os.dal.ModuloConexao;
import java.awt.Color;
import javafx.scene.control.Tooltip;
import javax.swing.JOptionPane;
import javax.swing.plaf.ToolTipUI;

/**
 *
 * @author André
 */
public class TelaLogin extends javax.swing.JFrame {

    Connection conexao = null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    public void logar() {
        String sql = "SELECT * FROM tbusuarios WHERE login = ? and senha = ?";
        try {
            pst = conexao.prepareStatement(sql);
            pst.setString(1, jtxtUsuario.getText().toUpperCase());
            pst.setString(2, jpfSenha.getText());
            rs = pst.executeQuery();
            if (rs.next()) {
                String perfil = rs.getString(6);
                //System.out.println(perfil);
                if (perfil.equals("Administrador")) {
                    TelaPrincipal TP = new TelaPrincipal();
                    TP.setVisible(true);
                    TelaPrincipal.menRelOS.setEnabled(true);
                    TelaPrincipal.jmItemNovoUsu.setEnabled(true);
                    TelaPrincipal.jlblUsuConectado.setText(rs.getString(2));
                    TelaPrincipal.jlblUsuConectado.setForeground(Color.BLUE);                                    
                    //this.hide();
                    this.dispose();
                    conexao.close();
                }
                else if(perfil.equals("Colaborador")){
                    TelaPrincipal TP = new TelaPrincipal();
                    TP.setVisible(true);  
                    TelaPrincipal.jlblUsuConectado.setText(rs.getString(2));                    
                    TelaPrincipal.jlblUsuConectado.setForeground(Color.RED);
                    this.dispose();
                    conexao.close();
                }
            }else {
                JOptionPane.showMessageDialog(null, "Usuário e/ou Senha estão Incorretos, verifique !");
                jtxtUsuario.setText("");
                jpfSenha.setText("");
                jtxtUsuario.requestFocus();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    /**
     * Creates new form TelaLogin
     */
    public TelaLogin() {
        initComponents();
        conexao = ModuloConexao.conector();
        // System.out.println(conexao); // Informa o Status da Conexão 
        // Verifica se o banco de dados está Disponível (Ativo) ou Inacessível (Inativo) 
        if (conexao != null) {
            jlblStatus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/amsistemas/os/icones/Banco-Disponivel.png")));
        } else {
            jlblStatus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/amsistemas/os/icones/Banco-Inacessivel.png")));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlblUsuTitulo = new javax.swing.JLabel();
        jlblSenhaTitulo = new javax.swing.JLabel();
        jtxtUsuario = new javax.swing.JTextField();
        btnEntrar = new javax.swing.JButton();
        jpfSenha = new javax.swing.JPasswordField();
        jlblStatus = new javax.swing.JLabel();
        jLblLogo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Acesso  | AM Sistemas ");
        setResizable(false);

        jlblUsuTitulo.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jlblUsuTitulo.setText("Usuário");

        jlblSenhaTitulo.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jlblSenhaTitulo.setText("Senha");

        jtxtUsuario.setBackground(new java.awt.Color(255, 255, 204));
        jtxtUsuario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtxtUsuario.setToolTipText("Informe o usuário credenciado");

        btnEntrar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnEntrar.setText("Entrar");
        btnEntrar.setToolTipText("Clique para logar");
        btnEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarActionPerformed(evt);
            }
        });

        jpfSenha.setBackground(new java.awt.Color(255, 255, 204));
        jpfSenha.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jpfSenha.setToolTipText("Informe a senha credenciada");

        jlblStatus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/amsistemas/os/icones/Banco-Disponivel.png"))); // NOI18N

        jLblLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/amsistemas/os/telas/LOGOMARCA.png"))); // NOI18N
        jLblLogo.setDisabledIcon(null);
        jLblLogo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLblLogo.setMaximumSize(new java.awt.Dimension(800, 800));
        jLblLogo.setMinimumSize(new java.awt.Dimension(800, 800));
        jLblLogo.setPreferredSize(new java.awt.Dimension(800, 800));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLblLogo, javax.swing.GroupLayout.DEFAULT_SIZE, 858, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(298, 298, 298)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jlblUsuTitulo)
                                    .addComponent(jlblSenhaTitulo)
                                    .addComponent(jtxtUsuario)
                                    .addComponent(jpfSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(66, 66, 66)
                                        .addComponent(btnEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(407, 407, 407)
                                .addComponent(jlblStatus)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlblUsuTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtxtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlblSenhaTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpfSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(btnEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlblStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarActionPerformed
        logar();
    }//GEN-LAST:event_btnEntrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEntrar;
    private javax.swing.JLabel jLblLogo;
    private javax.swing.JLabel jlblSenhaTitulo;
    private javax.swing.JLabel jlblStatus;
    private javax.swing.JLabel jlblUsuTitulo;
    private javax.swing.JPasswordField jpfSenha;
    private javax.swing.JTextField jtxtUsuario;
    // End of variables declaration//GEN-END:variables
}
