/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.amsistemas.os.telas;

import br.com.amsistemas.os.classes.PosicaoFormulario; /* Importa o Pacote de Classes, chamando o método criado junto */
import br.com.amsistemas.os.dal.ModuloConexao;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import java.sql.*;
//import net.sf.jasperreports.engine.JasperFillManager;
//import net.sf.jasperreports.engine.JasperPrint;
//import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author André
 */
public class TelaPrincipal extends javax.swing.JFrame {

    Connection conexao = null; 
    PosicaoFormulario PF = new PosicaoFormulario(); /* Referencia o Método na classe Principal */
    
    
    public TelaPrincipal() {
        initComponents();
        conexao = ModuloConexao.conector();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDP_AreaTra = new javax.swing.JDesktopPane();
        jPnl_BarraTar = new javax.swing.JPanel();
        jlblTituUsuLogado = new javax.swing.JLabel();
        jlblUsuConectado = new javax.swing.JLabel();
        jlblVersaoSistema = new javax.swing.JLabel();
        jlblSeparador1 = new javax.swing.JLabel();
        jlblSeparador2 = new javax.swing.JLabel();
        jmbMenuzinho = new javax.swing.JMenuBar();
        jmAbaArquivo = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jmItemNovoUsu = new javax.swing.JMenuItem();
        menRelOS = new javax.swing.JMenu();
        menRelServ = new javax.swing.JMenuItem();
        menRelCli = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jmAbaFerramenta = new javax.swing.JMenu();
        jmAbaAjuda = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jmAbaSair = new javax.swing.JMenu();
        jmItemDesloga = new javax.swing.JMenuItem();
        jmItemSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ordem de Serviço | AM Sistemas");
        setName("frmMDI"); // NOI18N
        setResizable(false);
        setSize(new java.awt.Dimension(1295, 666));

        jDP_AreaTra.setPreferredSize(new java.awt.Dimension(1280, 720));

        jPnl_BarraTar.setPreferredSize(new java.awt.Dimension(1290, 18));

        jlblTituUsuLogado.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlblTituUsuLogado.setText("Usuário:");

        jlblUsuConectado.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlblUsuConectado.setForeground(new java.awt.Color(255, 0, 0));
        jlblUsuConectado.setText("Aguardando conexão...");
        jlblUsuConectado.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        jlblVersaoSistema.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlblVersaoSistema.setText("Versão 1.0");

        jlblSeparador1.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jlblSeparador1.setForeground(new java.awt.Color(204, 204, 204));
        jlblSeparador1.setText("|");

        jlblSeparador2.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jlblSeparador2.setForeground(new java.awt.Color(204, 204, 204));
        jlblSeparador2.setText("|");

        javax.swing.GroupLayout jPnl_BarraTarLayout = new javax.swing.GroupLayout(jPnl_BarraTar);
        jPnl_BarraTar.setLayout(jPnl_BarraTarLayout);
        jPnl_BarraTarLayout.setHorizontalGroup(
            jPnl_BarraTarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnl_BarraTarLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jlblTituUsuLogado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlblUsuConectado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlblSeparador1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 966, Short.MAX_VALUE)
                .addComponent(jlblSeparador2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlblVersaoSistema, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPnl_BarraTarLayout.setVerticalGroup(
            jPnl_BarraTarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPnl_BarraTarLayout.createSequentialGroup()
                .addGap(0, 1, Short.MAX_VALUE)
                .addGroup(jPnl_BarraTarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblTituUsuLogado)
                    .addComponent(jlblUsuConectado)
                    .addComponent(jlblVersaoSistema)
                    .addComponent(jlblSeparador1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblSeparador2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jDP_AreaTra.setLayer(jPnl_BarraTar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDP_AreaTraLayout = new javax.swing.GroupLayout(jDP_AreaTra);
        jDP_AreaTra.setLayout(jDP_AreaTraLayout);
        jDP_AreaTraLayout.setHorizontalGroup(
            jDP_AreaTraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPnl_BarraTar, javax.swing.GroupLayout.DEFAULT_SIZE, 1295, Short.MAX_VALUE)
        );
        jDP_AreaTraLayout.setVerticalGroup(
            jDP_AreaTraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDP_AreaTraLayout.createSequentialGroup()
                .addGap(0, 627, Short.MAX_VALUE)
                .addComponent(jPnl_BarraTar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jmbMenuzinho.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jmAbaArquivo.setText("Arquivo");
        jmAbaArquivo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem1.setText("Novo Cliente");
        jMenuItem1.setToolTipText("Cadastrar um novo cliente");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jmAbaArquivo.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem2.setText("Nova Ordem de Serviço");
        jMenuItem2.setToolTipText("Cadastrar uma nova ordem de serviço");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jmAbaArquivo.add(jMenuItem2);

        jmItemNovoUsu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jmItemNovoUsu.setText("Novo Usuário");
        jmItemNovoUsu.setToolTipText("Cadastrar um novo usuário ao sistema");
        jmItemNovoUsu.setEnabled(false);
        jmItemNovoUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmItemNovoUsuActionPerformed(evt);
            }
        });
        jmAbaArquivo.add(jmItemNovoUsu);

        jmbMenuzinho.add(jmAbaArquivo);

        menRelOS.setText("Relatórios");
        menRelOS.setEnabled(false);
        menRelOS.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        menRelServ.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        menRelServ.setText("Gerar Relatório de Serviços");
        menRelServ.setToolTipText("Relatório de Serviços cadastrados");
        menRelServ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menRelServActionPerformed(evt);
            }
        });
        menRelOS.add(menRelServ);

        menRelCli.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        menRelCli.setText("Gerar Relatório de Clientes");
        menRelCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menRelCliActionPerformed(evt);
            }
        });
        menRelOS.add(menRelCli);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        jMenuItem3.setText("Gerar Relatório de Ordem de Serviço");
        menRelOS.add(jMenuItem3);

        jmbMenuzinho.add(menRelOS);

        jmAbaFerramenta.setText("Ferramentas");
        jmAbaFerramenta.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jmbMenuzinho.add(jmAbaFerramenta);

        jmAbaAjuda.setText("Ajuda");
        jmAbaAjuda.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_DOWN_MASK));
        jMenuItem5.setText("Sobre");
        jMenuItem5.setToolTipText("Informações sobre o sistema");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jmAbaAjuda.add(jMenuItem5);

        jmbMenuzinho.add(jmAbaAjuda);

        jmAbaSair.setText("Sair");
        jmAbaSair.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jmItemDesloga.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, java.awt.event.InputEvent.ALT_DOWN_MASK));
        jmItemDesloga.setText("Deslogar ");
        jmItemDesloga.setToolTipText("Desloga a conta do usuário");
        jmItemDesloga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmItemDeslogaActionPerformed(evt);
            }
        });
        jmAbaSair.add(jmItemDesloga);

        jmItemSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        jmItemSair.setText("Sair do Programa");
        jmItemSair.setToolTipText("Sair de toda a aplicação");
        jmItemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmItemSairActionPerformed(evt);
            }
        });
        jmAbaSair.add(jmItemSair);

        jmbMenuzinho.add(jmAbaSair);

        setJMenuBar(jmbMenuzinho);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDP_AreaTra, javax.swing.GroupLayout.DEFAULT_SIZE, 1295, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDP_AreaTra, javax.swing.GroupLayout.DEFAULT_SIZE, 673, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1311, 705));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
            
    private void jmItemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmItemSairActionPerformed
        int Sair = JOptionPane.showConfirmDialog(null,"Tem certeza que deseja encerrar todas as atividades no programa ?","GeOS | Sair", JOptionPane.YES_NO_OPTION);
        if(Sair == JOptionPane.YES_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_jmItemSairActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        TelaSobre TS = new TelaSobre();
        TS.setVisible(true);        
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jmItemDeslogaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmItemDeslogaActionPerformed
        int Deslogar = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja deslogar do sistema ?","GeOS | Deslogar do Sistema", JOptionPane.YES_NO_OPTION);
        if(Deslogar == JOptionPane.YES_OPTION){
            TelaLogin TL = new TelaLogin();
            TL.setVisible(true);
            this.hide();
        }              
    }//GEN-LAST:event_jmItemDeslogaActionPerformed

    private void jmItemNovoUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmItemNovoUsuActionPerformed
        /*TelaUsuario TUs = new TelaUsuario();
        TUs.setVisible(true);
        jDP_AreaTra.add(TUs);*/        
        TelaUsuario tela;
        PF.abrirFormulario(tela = new TelaUsuario(), jDP_AreaTra);
        
    }//GEN-LAST:event_jmItemNovoUsuActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        TelaCliente tela;
        PF.abrirFormulario(tela = new TelaCliente(), jDP_AreaTra);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        TelaOS tela;
        PF.abrirFormulario(tela = new TelaOS(), jDP_AreaTra);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void menRelCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menRelCliActionPerformed
        int Confirmar = JOptionPane.showConfirmDialog(null, "Confirmar a impressão deste relatório de Clientes ?", "Aviso de Impressão", JOptionPane.YES_NO_OPTION);
        
        if(Confirmar == JOptionPane.YES_OPTION){
            try {
                //JasperPrint print = JasperFillManager.fillReport("C:\\Users\\André\\JaspersoftWorkspace\\R-Clientes\\Relatorio-Cli.jasper", null, conexao);
                //JasperViewer.viewReport(print, false);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_menRelCliActionPerformed

    private void menRelServActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menRelServActionPerformed
        int Confirmar = JOptionPane.showConfirmDialog(null, "Confirmar a impressão deste relatório de Serviços ?", "Aviso de Impressão", JOptionPane.YES_NO_OPTION);
        
        if(Confirmar == JOptionPane.YES_OPTION){
            try {
                //JasperPrint print = JasperFillManager.fillReport("C:\\Users\\André\\JaspersoftWorkspace\\R-Clientes\\Relatorio_Serv.jasper", null, conexao);
                //JasperViewer.viewReport(print, false);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_menRelServActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDP_AreaTra;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPnl_BarraTar;
    private javax.swing.JLabel jlblSeparador1;
    private javax.swing.JLabel jlblSeparador2;
    private javax.swing.JLabel jlblTituUsuLogado;
    public static javax.swing.JLabel jlblUsuConectado;
    private javax.swing.JLabel jlblVersaoSistema;
    private javax.swing.JMenu jmAbaAjuda;
    private javax.swing.JMenu jmAbaArquivo;
    private javax.swing.JMenu jmAbaFerramenta;
    private javax.swing.JMenu jmAbaSair;
    private javax.swing.JMenuItem jmItemDesloga;
    public static javax.swing.JMenuItem jmItemNovoUsu;
    private javax.swing.JMenuItem jmItemSair;
    private javax.swing.JMenuBar jmbMenuzinho;
    private javax.swing.JMenuItem menRelCli;
    public static javax.swing.JMenu menRelOS;
    private javax.swing.JMenuItem menRelServ;
    // End of variables declaration//GEN-END:variables
}
